FROM ubuntu:16.04

RUN sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/" /etc/apt/sources.list \
    && sed -i "s/security.ubuntu.com/mirrors.aliyun.com/" /etc/apt/sources.list \
    && apt-get update \
    && apt-get upgrade -y python3 \
    && apt-get install -y build-essential python3-dev python3-venv vim

WORKDIR /tmp

