FROM ubuntu:18.04

ENV LD_LIBRARY_PATH /usr/local/lib
RUN sed -i "s/archive.ubuntu.com/mirrors.163.com/" /etc/apt/sources.list \
    && apt-get clean \
    && apt-get update \
    && apt-get install -y build-essential cmake vim-nox libboost-all-dev python3-dev \
    && mkdir -p /tmp/build

WORKDIR /tmp

