FROM ubuntu:16.04

ENV LD_LIBRARY_PATH /usr/local/lib
RUN sed -i "s/archive.ubuntu.com/mirrors.163.com/" /etc/apt/sources.list \
    && apt-get update \
    && apt-get upgrade -y python3 \
    && apt-get install -y build-essential libboost-all-dev python3-dev python3-venv python3-pip python3-setuptools python3-wheel

WORKDIR /tmp

